### ISSUE TITLE
Can't understand these html files

### ISSUE THREAD

**Issue by SravanVuppalapati** [AhmedIsmailKhalid/IBM-Applied-AI-Specialization#1]
Hello Sir,this is Sravan.I can't get complete the quiz coz when I open these files,it shows raw data.So can u tell me how to get the answers for quizes from these raw data

**Comment by AhmedIsmailKhalid** [comment]
Hi Sravan. Unfortunately, you cannot get the answers to the quiz questions using the raw data. In order to get the answers you need both the .html file and the quiz files folder. So for example you want to get the answers to the week 3 quiz for the 1st course. So if you go to the folder "Course 1 ─ Introduction to Artificial Intelligence (AI)" you will see the folder "Week 3 ─ AI Issues, Concerns and Ethical Considerations". Inside this folder you will see another folder called "Week 3 Quiz ─ AI Issues, Ethics and Bias_files". You need to download all the files inside this folder along with the html file to download the html page that has the quiz answers. This is because I saved the entire quiz page. I tried other options including saving the page as pdf but that resulted in rendering the page unreadable.

I understand that this is a HUGE problem. However, there is a workaround present that you can use to make things a lot easier for you. Just navigate to the week of the course you want, copy the url and paste then url [https://minhaskamal.github.io/DownGit/#/home](url)

**Comment by AhmedIsmailKhalid** [comment]
You can also download gitzip chrome extension to download the html file along with the folder. The link along with the instructions can be found at : [https://chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn?hl=en](url)

**Comment by SravanVuppalapati** [comment]
Thanq you for your concern.But I am able to see only one question.
